# Basic site settings
title: Pocket Flow
tagline: A 100-line LLM framework
description: Minimalist LLM Framework in 100 Lines, Enabling LLMs to Program Themselves

# Theme settings
remote_theme: just-the-docs/just-the-docs

# Navigation
nav_sort: case_sensitive

# Aux links (shown in upper right)
aux_links:
  "View on GitHub":
    - "//github.com/the-pocket/PocketFlow"

# Color scheme
color_scheme: light

# Author settings
author:
  name: Zachary Huang
  url: https://www.columbia.edu/~zh2408/
  twitter: ZacharyHuang12

# Mermaid settings
mermaid:
  version: "9.1.3" # Pick the version you want
  # Default configuration
  config: |
    directionLR

# Callouts settings
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  best-practice:
    title: Best Practice
    color: green

# The custom navigation
nav:
  - Home: index.md # Link to your main docs index
  - GitHub: "https://github.com/the-pocket/PocketFlow"
  - Discord: "https://discord.gg/hUHHE9Sa6T"
